apiVersion: 1

groups:
  - orgId: 1
    name: 'FastAPI Alerts'
    folder: 'Alerts'
    interval: 10s
    rules:
      - uid: 'fastapi_high_error_rate'
        title: 'High 5xx Error Rate'
        condition: 'A'
        data:
          - refId: 'A'
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: 'Prometheus'
            model:
              editorMode: 'code'
              expr: 'rate(fastapi_requests_total{status=~"5.."}[1m]) > 0.1'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: 'A'
        noDataState: 'OK'
        execErrState: 'Error'
        for: '10s'
        labels:
          severity: 'critical'
        annotations:
          summary: 'Обнаружен всплеск 500 ошибок в FastAPI!'
