server {
    listen 80;
    server_name localhost;

    # Логирование запросов
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Все запросы перенаправляем на сервис приложения по имени "app" из docker-compose
    location / {
        proxy_pass http://app:8000;
        
        # Передаем оригинальные заголовки клиента
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
